#application: ASSISTRON
application: team07-govchal00
version: 1
runtime: php
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /static
  static_dir: static

# Serve php scripts.
- url: /(.+\.php)$
  script: \1

# - url: /(.+\.html)$
  # static_files: \1
  
- url: /css
  static_dir: css
  
- url: /js
  static_dir: js

- url: /fonts
  static_dir: fonts

- url: /checkin
  script: /php/checkin.php

- url: /report_need
  script: /php/report_need.php

- url: /checkout
  script: /php/checkout.php
  
- url: .*
  script: index.php
