<?php

namespace CW\Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * Human_JobLead
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Human_JobLead extends EntityRepository
{
}
