<?php

namespace CW\Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * JobLeadType
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobLeadType extends EntityRepository
{
}
