<?php

namespace CW\Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * JobLead
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobLead extends EntityRepository
{
}
